"""Synthetic content shared by the seed_demo_data and simulate_traffic commands."""

DEMO_EMAIL_DOMAIN = "demo.cookoverflow.test"
DEMO_PASSWORD = "cookdemo123"

# (username, first, last, gender, city, country, cuisine, about, colour)
USERS = [
    ("lina_haddad", "Lina", "Haddad", "female", "Ramallah", "Palestine", "palestinian",
     "Cooking my teta's recipes so they never get lost.", (176, 58, 46)),
    ("omar_khalil", "Omar", "Khalil", "male", "Amman", "Jordan", "jordanian",
     "Weekend griller, weekday stew maker.", (160, 82, 45)),
    ("sofia_rossi", "Sofia", "Rossi", "female", "Naples", "Italy", "italian",
     "Pasta by hand, sauce from scratch, no shortcuts.", (192, 57, 43)),
    ("kenji_tanaka", "Kenji", "Tanaka", "male", "Osaka", "Japan", "japanese",
     "Home cook from Osaka. Street food is my love language.", (44, 62, 80)),
    ("maria_garcia", "Maria", "Garcia", "female", "Seville", "Spain", "spanish",
     "Tapas, paella and long Sunday lunches.", (211, 84, 0)),
    ("arjun_mehta", "Arjun", "Mehta", "male", "Mumbai", "India", "indian",
     "Spice cabinet with 40 jars and counting.", (230, 126, 34)),
    ("chloe_martin", "Chloe", "Martin", "female", "Lyon", "France", "french",
     "Butter is a food group. Pastry student.", (125, 60, 152)),
    ("daniel_okafor", "Daniel", "Okafor", "male", "Lagos", "Nigeria", "nigerian",
     "Jollof ambassador. Will debate you about it.", (39, 174, 96)),
    ("yasmin_nasser", "Yasmin", "Nasser", "female", "Cairo", "Egypt", "egyptian",
     "Street food from Cairo, cooked at home.", (22, 160, 133)),
    ("alex_johnson", "Alex", "Johnson", "male", "Austin", "USA", "american",
     "Low and slow BBQ and comfort food.", (41, 128, 185)),
]

# cuisine -> [(dish, course, vegetarian, ingredients, steps)]
DISHES = {
    "palestinian": [
        ("Maqluba", "dinner", False,
         ["rice", "chicken", "eggplant", "cauliflower", "onion", "allspice", "garlic"],
         ["Fry the eggplant and cauliflower until golden.",
          "Layer chicken, vegetables and washed rice in a deep pot.",
          "Cover with spiced stock and simmer for 40 minutes.",
          "Rest 10 minutes, then flip the pot onto a big tray."]),
        ("Musakhan", "dinner", False,
         ["chicken", "onion", "sumac", "olive oil", "taboon bread", "pine nuts"],
         ["Roast the chicken with sumac, allspice and olive oil.",
          "Cook a mountain of onions slowly in olive oil and sumac.",
          "Spread the onions on the bread and top with chicken.",
          "Bake for 10 minutes and finish with toasted pine nuts."]),
        ("Mujaddara", "lunch", True,
         ["lentils", "rice", "onion", "cumin", "olive oil"],
         ["Boil the lentils until almost tender.",
          "Add rice, cumin and water, then cook until fluffy.",
          "Fry sliced onions until deep brown and crispy.",
          "Serve topped with the onions and a cucumber yogurt salad."]),
        ("Knafeh", "dessert", True,
         ["kataifi", "akkawi cheese", "butter", "sugar syrup", "pistachio"],
         ["Soak the cheese overnight to remove the salt.",
          "Toss shredded kataifi with melted butter and press into a pan.",
          "Add the cheese and bake until golden underneath.",
          "Flip, pour over warm syrup and sprinkle pistachio."]),
        ("Fattoush", "salad", True,
         ["tomato", "cucumber", "lettuce", "radish", "sumac", "pita", "lemon"],
         ["Toast or fry torn pita until crunchy.",
          "Chop the vegetables into big pieces.",
          "Whisk lemon, olive oil, garlic and sumac.",
          "Toss everything right before serving."]),
    ],
    "jordanian": [
        ("Mansaf", "dinner", False,
         ["lamb", "jameed", "rice", "shrak bread", "almonds", "ghee"],
         ["Simmer the lamb until tender.",
          "Dissolve the jameed and cook it with the lamb broth.",
          "Cook rice with ghee and turmeric.",
          "Layer bread, rice and lamb, then pour over the jameed sauce."]),
        ("Galayet Bandora", "breakfast", True,
         ["tomato", "garlic", "chili", "olive oil", "onion"],
         ["Sweat garlic and onion in olive oil.",
          "Add chopped tomatoes and cook until jammy.",
          "Season with chili and salt.",
          "Eat straight from the pan with warm bread."]),
        ("Zarb", "dinner", False,
         ["lamb", "chicken", "potato", "onion", "carrot", "baharat"],
         ["Marinate the meat in baharat and olive oil.",
          "Load meat and vegetables onto the zarb rack.",
          "Cook underground (or in a sealed oven) for 3 hours.",
          "Serve with rice and yogurt."]),
        ("Mutabbal", "appetizer", True,
         ["eggplant", "tahini", "garlic", "lemon", "yogurt"],
         ["Char the eggplants over an open flame.",
          "Peel and mash the flesh.",
          "Mix with tahini, garlic, lemon and yogurt.",
          "Finish with olive oil and pomegranate seeds."]),
        ("Hareeseh", "dessert", True,
         ["semolina", "yogurt", "sugar", "coconut", "almonds", "sugar syrup"],
         ["Mix semolina, sugar, yogurt and coconut.",
          "Spread in a tray and rest 30 minutes.",
          "Press an almond into every square and bake.",
          "Pour cold syrup over the hot cake."]),
    ],
    "italian": [
        ("Pasta alla Norma", "dinner", True,
         ["pasta", "eggplant", "tomato", "garlic", "basil", "ricotta salata"],
         ["Fry cubed eggplant until golden.",
          "Make a quick tomato and garlic sauce.",
          "Toss pasta with the sauce and eggplant.",
          "Top with basil and grated ricotta salata."]),
        ("Risotto ai Funghi", "dinner", True,
         ["arborio rice", "mushrooms", "onion", "white wine", "parmesan", "butter"],
         ["Saute mushrooms and set aside.",
          "Toast the rice with onion, then add wine.",
          "Add hot stock one ladle at a time for 18 minutes.",
          "Stir in butter, parmesan and the mushrooms."]),
        ("Pizza Margherita", "dinner", True,
         ["flour", "yeast", "tomato", "mozzarella", "basil", "olive oil"],
         ["Make the dough and let it rise for 24 hours.",
          "Stretch by hand, never with a rolling pin.",
          "Top with crushed tomatoes and torn mozzarella.",
          "Bake as hot as your oven goes and finish with basil."]),
        ("Tiramisu", "dessert", True,
         ["mascarpone", "eggs", "sugar", "savoiardi", "espresso", "cocoa"],
         ["Whip egg yolks with sugar, then fold in mascarpone.",
          "Dip the biscuits quickly in espresso.",
          "Layer biscuits and cream twice.",
          "Chill overnight and dust with cocoa."]),
        ("Minestrone", "soup", True,
         ["beans", "carrot", "celery", "zucchini", "tomato", "pasta", "parmesan"],
         ["Soften carrot, celery and onion in olive oil.",
          "Add tomatoes, beans and stock.",
          "Simmer, then add zucchini and small pasta.",
          "Serve with a parmesan rind melted in."]),
    ],
    "japanese": [
        ("Chicken Katsu Curry", "dinner", False,
         ["chicken", "panko", "eggs", "curry roux", "potato", "carrot", "rice"],
         ["Simmer onion, potato and carrot, then melt in the curry roux.",
          "Coat the chicken in flour, egg and panko.",
          "Fry until golden and slice.",
          "Serve over rice with plenty of curry sauce."]),
        ("Miso Soup", "soup", True,
         ["dashi", "miso", "tofu", "wakame", "spring onion"],
         ["Heat the dashi without boiling.",
          "Add tofu cubes and wakame.",
          "Whisk in miso off the heat.",
          "Top with spring onion."]),
        ("Okonomiyaki", "dinner", False,
         ["cabbage", "flour", "eggs", "pork belly", "okonomi sauce", "mayonnaise"],
         ["Mix flour, dashi and eggs into a batter.",
          "Fold in a lot of shredded cabbage.",
          "Cook on a griddle topped with pork belly.",
          "Finish with sauce, mayonnaise and bonito flakes."]),
        ("Tamagoyaki", "breakfast", True,
         ["eggs", "dashi", "soy sauce", "mirin", "sugar"],
         ["Beat eggs with dashi, mirin and soy sauce.",
          "Pour a thin layer into the square pan.",
          "Roll it up and add another layer.",
          "Repeat, then rest in a bamboo mat."]),
        ("Onigiri", "lunch", False,
         ["rice", "nori", "salmon", "salt", "sesame"],
         ["Cook short grain rice and let it cool slightly.",
          "Wet and salt your hands.",
          "Shape triangles around grilled salmon.",
          "Wrap with nori right before eating."]),
    ],
    "spanish": [
        ("Paella Valenciana", "dinner", False,
         ["bomba rice", "chicken", "rabbit", "green beans", "saffron", "paprika"],
         ["Brown the meat in a wide paella pan.",
          "Add beans, tomato and paprika.",
          "Pour in stock with saffron, then scatter the rice.",
          "Do not stir. Let the socarrat form at the end."]),
        ("Tortilla Espanola", "lunch", True,
         ["potato", "eggs", "onion", "olive oil", "salt"],
         ["Slowly poach potatoes and onion in olive oil.",
          "Mix them into the beaten eggs and rest 10 minutes.",
          "Cook in a pan until the edges set.",
          "Flip with a plate and cook the other side."]),
        ("Gazpacho", "soup", True,
         ["tomato", "cucumber", "pepper", "garlic", "sherry vinegar", "olive oil"],
         ["Chop ripe tomatoes, cucumber and pepper.",
          "Blend with garlic, vinegar and olive oil.",
          "Strain for a silky texture.",
          "Chill for at least two hours."]),
        ("Patatas Bravas", "appetizer", True,
         ["potato", "paprika", "tomato", "garlic", "mayonnaise"],
         ["Parboil the potato chunks.",
          "Fry until very crispy.",
          "Make a smoky paprika tomato sauce.",
          "Serve with sauce and garlic mayonnaise."]),
        ("Churros con Chocolate", "dessert", True,
         ["flour", "water", "sugar", "dark chocolate", "milk", "cinnamon"],
         ["Make a thick dough with boiling water and flour.",
          "Pipe into hot oil and fry until golden.",
          "Roll in cinnamon sugar.",
          "Dip in thick hot chocolate."]),
    ],
    "indian": [
        ("Chana Masala", "dinner", True,
         ["chickpeas", "onion", "tomato", "ginger", "garlic", "garam masala"],
         ["Fry onion until deep golden.",
          "Add ginger, garlic and spices.",
          "Cook down the tomatoes, then add chickpeas.",
          "Simmer and finish with garam masala and coriander."]),
        ("Butter Chicken", "dinner", False,
         ["chicken", "yogurt", "butter", "tomato", "cream", "kasuri methi"],
         ["Marinate chicken in yogurt and spices overnight.",
          "Grill or pan-roast until charred.",
          "Simmer a tomato, butter and cream sauce.",
          "Add chicken and crushed kasuri methi."]),
        ("Masala Dosa", "breakfast", True,
         ["rice", "urad dal", "potato", "mustard seeds", "curry leaves"],
         ["Soak and grind rice and dal, then ferment overnight.",
          "Make a spiced potato filling.",
          "Spread the batter thin on a hot pan.",
          "Fill, fold and serve with chutney and sambar."]),
        ("Palak Paneer", "dinner", True,
         ["spinach", "paneer", "onion", "garlic", "cream", "cumin"],
         ["Blanch spinach and blend smooth.",
          "Fry onion, garlic and cumin.",
          "Add the spinach puree and simmer.",
          "Stir in seared paneer cubes and cream."]),
        ("Mango Lassi", "drink", True,
         ["mango", "yogurt", "milk", "cardamom", "sugar"],
         ["Blend mango with yogurt and milk.",
          "Add cardamom and sugar to taste.",
          "Blend again with ice.",
          "Serve cold."]),
    ],
    "french": [
        ("Ratatouille", "dinner", True,
         ["eggplant", "zucchini", "pepper", "tomato", "onion", "thyme"],
         ["Cook each vegetable separately in olive oil.",
          "Make a base of onion, garlic and tomato.",
          "Combine everything with thyme.",
          "Simmer gently. It is better the next day."]),
        ("Quiche Lorraine", "lunch", False,
         ["flour", "butter", "eggs", "cream", "bacon", "gruyere"],
         ["Blind bake a buttery shortcrust.",
          "Fry the bacon lardons.",
          "Whisk eggs with cream and nutmeg.",
          "Fill, add gruyere and bake until just set."]),
        ("Coq au Vin", "dinner", False,
         ["chicken", "red wine", "mushrooms", "bacon", "shallots", "thyme"],
         ["Marinate the chicken in red wine overnight.",
          "Brown chicken, bacon and shallots.",
          "Braise in the wine for 90 minutes.",
          "Add mushrooms at the end."]),
        ("Crepes", "dessert", True,
         ["flour", "eggs", "milk", "butter", "sugar"],
         ["Whisk a smooth, thin batter and rest it.",
          "Heat a buttered pan.",
          "Swirl in a thin layer and cook one minute each side.",
          "Fill with lemon and sugar or chocolate."]),
        ("French Onion Soup", "soup", True,
         ["onion", "butter", "beef stock", "baguette", "gruyere"],
         ["Caramelise onions slowly for an hour.",
          "Deglaze and add stock.",
          "Top bowls with baguette slices and gruyere.",
          "Grill until bubbling."]),
    ],
    "nigerian": [
        ("Jollof Rice", "dinner", True,
         ["rice", "tomato", "pepper", "scotch bonnet", "onion", "thyme"],
         ["Blend tomatoes, peppers and scotch bonnet.",
          "Fry the blend down until the oil separates.",
          "Add stock and washed rice.",
          "Cover tightly and steam on low heat."]),
        ("Egusi Soup", "dinner", False,
         ["egusi", "spinach", "palm oil", "beef", "stockfish", "crayfish"],
         ["Cook the meat with onion and seasoning.",
          "Fry ground egusi in palm oil.",
          "Add stock, meat and crayfish.",
          "Stir in spinach and simmer briefly."]),
        ("Suya", "dinner", False,
         ["beef", "yaji spice", "peanuts", "onion", "ginger"],
         ["Slice the beef very thin.",
          "Coat generously with yaji spice mix.",
          "Grill over high heat on skewers.",
          "Serve with raw onion and more yaji."]),
        ("Puff-Puff", "snack", True,
         ["flour", "yeast", "sugar", "nutmeg", "water"],
         ["Mix a soft, sticky dough.",
          "Let it rise until doubled.",
          "Scoop balls into hot oil.",
          "Fry until golden and puffed."]),
        ("Moi Moi", "lunch", True,
         ["beans", "pepper", "onion", "palm oil", "eggs"],
         ["Peel and blend the beans with peppers.",
          "Season and add palm oil.",
          "Pour into leaves or ramekins.",
          "Steam for about an hour."]),
    ],
    "egyptian": [
        ("Koshari", "dinner", True,
         ["rice", "lentils", "pasta", "chickpeas", "tomato", "onion", "vinegar"],
         ["Cook rice, lentils and pasta separately.",
          "Fry onions until crispy.",
          "Make a garlicky tomato vinegar sauce.",
          "Layer everything and top with onions."]),
        ("Ful Medames", "breakfast", True,
         ["fava beans", "garlic", "cumin", "lemon", "olive oil"],
         ["Warm the fava beans in their liquid.",
          "Mash roughly with garlic and cumin.",
          "Add lemon and olive oil.",
          "Serve with baladi bread and pickles."]),
        ("Molokhia", "dinner", False,
         ["molokhia", "chicken", "garlic", "coriander", "ghee"],
         ["Make a rich chicken stock.",
          "Stir in the chopped molokhia.",
          "Fry garlic and coriander in ghee.",
          "Pour the tasha over the soup with a gasp."]),
        ("Ta'ameya", "breakfast", True,
         ["fava beans", "parsley", "coriander", "onion", "garlic", "sesame"],
         ["Soak dried fava beans overnight.",
          "Blend with herbs, onion and garlic.",
          "Shape patties and press in sesame.",
          "Fry until crisp and bright green inside."]),
        ("Om Ali", "dessert", True,
         ["puff pastry", "milk", "cream", "sugar", "nuts", "raisins"],
         ["Bake and break up the puff pastry.",
          "Mix with nuts and raisins.",
          "Pour over sweetened hot milk.",
          "Top with cream and bake until golden."]),
    ],
    "american": [
        ("Texas Brisket", "dinner", False,
         ["brisket", "salt", "black pepper", "wood smoke"],
         ["Trim the fat cap to a quarter inch.",
          "Season with only salt and coarse black pepper.",
          "Smoke at 250F until the bark sets, then wrap.",
          "Rest for at least 2 hours before slicing."]),
        ("Mac and Cheese", "dinner", True,
         ["macaroni", "cheddar", "milk", "butter", "flour", "mustard"],
         ["Make a roux with butter and flour.",
          "Whisk in milk until thick.",
          "Melt in lots of cheddar and a little mustard.",
          "Fold in macaroni and bake with breadcrumbs."]),
        ("Buttermilk Pancakes", "breakfast", True,
         ["flour", "buttermilk", "eggs", "butter", "baking soda", "maple syrup"],
         ["Mix dry and wet ingredients separately.",
          "Combine gently, lumps are fine.",
          "Cook on a medium griddle until bubbles form.",
          "Flip once and serve with maple syrup."]),
        ("Chili con Carne", "dinner", False,
         ["beef", "beans", "tomato", "chili powder", "cumin", "onion"],
         ["Brown the beef in batches.",
          "Cook onion, garlic and spices.",
          "Add tomatoes, beans and the beef.",
          "Simmer for 2 hours, stirring now and then."]),
        ("Pecan Pie", "dessert", True,
         ["pecans", "eggs", "butter", "brown sugar", "corn syrup", "flour"],
         ["Blind bake the crust.",
          "Whisk eggs, sugar, syrup and melted butter.",
          "Add toasted pecans.",
          "Bake until just set in the middle."]),
    ],
}

RECIPE_INTROS = [
    "Sharing my family recipe for {dish}. It never fails.",
    "{dish} tonight! Here's exactly how I make it.",
    "Finally wrote down my {dish} recipe after years of cooking it by feel.",
    "Rainy day = {dish} day. Recipe below.",
    "My take on classic {dish}. Simple, honest, delicious.",
    "Friends kept asking, so here's my {dish}.",
]

TRIED_POSTS = [
    "Tried making {dish} from @{author}'s recipe and wow. Adding it to my weekly rotation.",
    "First attempt at {dish} (thanks @{author}!). Not perfect but the family finished it all.",
    "Cooked {dish} for friends tonight using @{author}'s steps. Everyone asked for the recipe.",
    "Weekend project: {dish}. Followed @{author} and it came out better than the restaurant.",
]

TIPS = [
    "Kitchen tip: salt your pasta water until it tastes like the sea.",
    "Kitchen tip: let meat rest after cooking. The juices stay inside, not on the board.",
    "Kitchen tip: toast whole spices in a dry pan before grinding. Night and day difference.",
    "Kitchen tip: keep a jar of caramelised onions in the fridge. Instant flavour for anything.",
    "Kitchen tip: a squeeze of lemon at the end wakes up almost any dish.",
    "Kitchen tip: freeze leftover herbs in olive oil in an ice cube tray.",
    "Kitchen tip: pat vegetables dry before roasting if you want them crispy.",
    "Kitchen tip: use the back of your knife to move chopped food, it keeps the edge sharp.",
    "Kitchen tip: rest your pancake and crepe batter for 30 minutes.",
    "Kitchen tip: day-old rice makes the best fried rice.",
    "Kitchen tip: add a spoon of the pasta water to your sauce to make it glossy.",
    "Kitchen tip: store tomatoes out of the fridge for better flavour.",
    "Kitchen tip: grate frozen butter into flour for the flakiest pastry.",
    "Kitchen tip: soak dried beans overnight with a pinch of baking soda.",
    "Kitchen tip: taste as you go. Recipes are a guide, your tongue is the boss.",
    "Kitchen tip: a hot pan and cold oil stop things from sticking.",
    "Kitchen tip: add garlic after the onions, it burns much faster.",
    "Kitchen tip: keep your knives sharp. Dull knives slip and cut you.",
    "Kitchen tip: brown butter makes cookies taste like toffee.",
    "Kitchen tip: cook eggs low and slow for the creamiest scramble.",
]

QUESTIONS = [
    "Question for everyone: what's a good substitute for {ingredient}?",
    "What's your go-to weeknight dinner that takes under 30 minutes?",
    "Cast iron or non-stick for everyday cooking? Convince me.",
    "Can I freeze {dish}, or does it get soggy?",
    "What spice do you use way more than everyone else?",
    "Best way to reheat rice without it drying out?",
    "Any tips for cooking {ingredient} without it going bitter?",
    "Looking for a vegetarian main that even meat lovers enjoy. Ideas?",
    "How do you keep homemade bread fresh for more than a day?",
    "Which dish from your childhood do you still crave?",
]

COMMENTS = [
    "This looks amazing!",
    "Saving this for the weekend.",
    "My family loved it, thank you for sharing!",
    "The photo alone made me hungry.",
    "Finally a recipe that actually works.",
    "I added a bit more garlic and it was perfect.",
    "Made it twice this week already.",
    "Clear steps, easy to follow. Thanks!",
    "This is exactly how my grandmother made it.",
    "Beautiful plating!",
    "Trying this tonight, wish me luck.",
    "How many people does this serve?",
    "Can I make this ahead of time?",
    "That colour is perfect.",
    "You never miss!",
    "Great tip, I never thought of that.",
    "Been doing this for years, works every time.",
    "Following. I want to know too!",
    "Adding this to my list.",
    "Wow, restaurant level.",
]

COMMENT_TEMPLATES = [
    "Made your {dish} last night and it disappeared in 10 minutes!",
    "What can I use instead of {ingredient}?",
    "Is fresh {ingredient} a must or will something else work?",
    "Your {dish} reminds me of home.",
    "I never knew {dish} could be this easy.",
    "Do you think {dish} would work in an air fryer?",
]

CONVERSATIONS = [
    ["Hi {b}! Your {dish} looks incredible.",
     "Thanks {a}! It's my mum's recipe.",
     "Would you share the spice mix?",
     "Sure, I'll write it down for you tonight."],
    ["Are you coming to the potluck on Friday?",
     "Yes! I'm bringing {dish}.",
     "Perfect, then I'll do dessert."],
    ["Quick question: what pan do you use for {dish}?",
     "A heavy cast iron one, it holds the heat well.",
     "Great, I have one. Thanks!"],
    ["I tried your {dish}, it was a hit!",
     "So happy to hear that!",
     "Next time I'll double the recipe."],
    ["Where do you buy your spices?",
     "A small market near my place, everything is fresh there.",
     "Lucky! Mine are all from the supermarket.",
     "Toast them first, it helps a lot."],
    ["Want to do a cooking video together sometime?",
     "I'd love that! Maybe {dish}?",
     "Deal. Let's plan it next week."],
]

SEARCHES = [
    "garlic-onion", "rice-chicken", "eggs-flour", "tomato-basil", "lentils",
    "chickpeas-cumin", "cheese", "chocolate", "yogurt-mint", "potato-paprika",
]
